### ISSUE TITLE
testing. Configuración de mplayer

### ISSUE THREAD

**Issue by rripio** [AudioHumLab/FIRtro#1]
Hola, esta línea de .mplayer/config , ¿es importante para las conexiones automágicas de mplayer?
`ao=jack:name=mplayer:noconnect`

**Comment by Rsantct** [comment]
Hola.

El archivo `.mplayer/config` viene heredado de la versión inicial de FIRrtro. Actualmente el arranque de mplayer en la branch testing se maneja en `initfirtro.py` (el código incluye comentarios) de manera que se sobreescribe lo configurado en `.mplayer/config`.

Es una solución pendiente de validación, no obstante. En caso que prospere, probablemente sea innecesario mantener `.mplayer/config`.

**Comment by rripio** [comment]
El 17 de agosto de 2017, 22:27, Rsantct <notifications@github.com> escribió:

> Hola.
>
> El archivo .mplayer/config viene heredado de la versión inicial de
> FIRrtro. Actualmente el arranque de mplayer en la branch testing se maneja
> en initfirtro.py (el código incluye comentarios) de manera que se
> sobreescribe lo configurado en .mplayer/config.
>
Pero, ¿se sobreescribe todo? Supongo que solo lo referente a las conexiones
jack, ¿no?

-- 
Roberto Ripio

**Comment by Rsantct** [comment]
Creo que en testing no se toma en cuenta nada del archivo `.mplayer/config`, de hecho la única línea descomentada podría estarlo. En el propio archivo hay notas explicativas (wip).

**Comment by rripio** [comment]
Está bien comentado el código, queda claro que carga los ajustes que estén en el config, y que no se refieran a los puertos de conexión.
Concretamente está la opción -profile, que supongo que deberá existir, aunque tal vez cargue dando un error.
Me parece que así está bien.

**Comment by Rsantct** [comment]
Aprovechando esta consulta, se ha revisado:
- bin/initfirtro.py: limpieza de la sección de mplayer
- .mplayer/config: limpieza de lo legacy para claridad
A la espera de aprobación...

**Comment by rripio** [comment]
Perfecto: Que los puertos de salida estén en ~/.mplater/config tiene una ventaja, y es que se asignan o simplemente se aceptan y se saben, de cara a escribir los archivos de inputs. Antes no se sabía salvo comprobación empírica y habría que haber hecho una nota de aviso, que ya no hace falta.

Aunque en realidad en el apartado de _~/audio/inputs_ se podría decir algo sobre dónde mirar los nombres de puertos de mpd y mplayer, y además dejar unas configuraciones por defecto comentadas que funcionen. En mi fork voy haciendo estas cosillas que te mandaré como pull request, cuando me aclare cómo.

Anoche mismo tuve que cambiar mis _inputs_ para adaptarlas a las que generaba mplayer e initfirtro aceptaba.

Muchas gracias, muy bien ahora.

**Comment by Rsantct** [comment]
Tal como propones, se ha ampliado información sobre el nombre de los puertos y dónde están definidos en ~/audio/inputs

**Comment by Rsantct** [comment]
Hola cierro esta issue/question, creo que está resuelta con lo último. He añadido algún matiz en `audio/inputs.example`. Así podemos centrarnos mejor en las issues abiertas. Si hubiera dudas la reabrimos.
