### ISSUE TITLE
master: retoques a la actualización

### ISSUE THREAD

**Issue by rripio** [AudioHumLab/FIRtro#14]
Parece que no se conserva www/config/config.ini al actualizar.

**Comment by Rsantct** [comment]
oops, se corrige actualizaFIRtro.sh

**Comment by rripio** [comment]
Hola, reabro porque en la última actualización me ha vuellto a machacar _www/config/config.ini_. Cuando puedas échale un vistazo.

**Comment by rripio** [comment]
Y recierro porque al volver a actualizar va bien. Sería un lío mío con versiones en directorios. Ea.
