### ISSUE TITLE
Se cambia el estado de mute al variar el volumen

### ISSUE THREAD

**Issue by rripio** [AudioHumLab/FIRtro#19]
Hacer un cambio de volumen mientras el audio está en mute provoca salir del estado de mute. Creo que deberían ser independientes. La metáfora del equipo hi-fi, que es el modelo general que se persigue, funciona así. También está claro que puedo querer poner el equipo a un volumen conocido (p.ej. para cine) con el sonido apagado.

No sé si ponerlo como bug o como feature request, no recuerdo cómo estaba antes, pero sí creo que debe cambiarse.

He creado la etiqueta feature request, más clara que enhancement, que puede quedar para mejoras del código como la que lo usa ahora. También he puesto master como milestone, a falta de acordar una release, para saber a qué rama nos referimos.

**Comment by Rsantct** [comment]
queda resuelto en el reciente merge en master
Probadlo plis

**Comment by rripio** [comment]
¡Gracias!

**Comment by Rsantct** [comment]
yugüelcom :-)

**Comment by rripio** [comment]
Funciona.
