### ISSUE TITLE
El instalador copia todo ~/tmp en ~

### ISSUE THREAD

**Issue by rripio** [AudioHumLab/FIRtro#21]
@Rsantct si crees que tiene que ser así lo cerramos de inmediato. No tengo por qué almacenar cosas en tmp, y lo hago :-) de modo que me las vuelca todas al home.

Pero: el hecho de que copie el zip recién bajado a ~ también es raro, te lo deja ahí sin hacer limpieza. Si pudiera operar desde ~/tmp sin más estaría bien.

**Comment by Rsantct** [comment]
oooops: habia un bug al hacer la copia de los archivos ocultos, queda corregido

**Comment by Rsantct** [comment]
las pruebas son buenas
