### ISSUE TITLE
Ligadura del volumen del FIRtro y el de mpd

### ISSUE THREAD

**Issue by rripio** [AudioHumLab/FIRtro#22]
Variar el volumen en el FIRtro produce un cambio en el volumen virtual de mpd. Pero la recíproca no es cierta. Manipular el volumen de mpd no varía el volumen del FIRtro, con lo que no tiene ningún efecto.

**Comment by Rsantct** [comment]
¿Tienes puesto en `audio/config`?:

    mpd_volume_linked2firtro = True

**Comment by rripio** [comment]
Ooops, era eso, ¡gracias!

Está genial esta feature.
